### PR TITLE
Add mversion as its a hard dependency for releasing

### PR DESCRIPTION
**Pull request by hmgibson23**
\cc @cutandpastey 

Opinionated build coming soon

### CODE REVIEW

**Comment by cutandpastey** [comment]
coolbeans :+1:

**Comment by hmgibson23** [comment]
Do we need to release it or anything like that?

On 2 March 2015 at 15:36, Jon Parsons notifications@github.com wrote:

> coolbeans [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/grunt-init-scribe-plugin/pull/2#issuecomment-76733245
> .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by cutandpastey** [comment]
No, but you will need to update the repo in `~/.grunt-init/grunt-init-scribe-plugin`.  We should maybe think of having some `bin` scripts for updating?

**Comment by hmgibson23** [comment]
Yeah sounds good. I'll make an issue

On 2 March 2015 at 15:46, Jon Parsons notifications@github.com wrote:

> No, but you will need to update the repo in
> ~/.grunt-init/grunt-init-scribe-plugin. We should maybe think of having
> some bin scripts for updating?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardian/grunt-init-scribe-plugin/pull/2#issuecomment-76735392
> .

## 

---

Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.

Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
